# -*- coding: utf-8 -*-
"""Ia-Colores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJzLQpdEXCXbdZK8w2XL9zQVGHaRLeoD
"""

!git clone https://github.com/jojeda5171/IA-Colores

!python IA-Colores/main/main.py

